# Generated by Django 4.0.10 on 2024-10-29 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 10, 29)),
        ),
    ]
